### ISSUE TITLE
Cannot find module 'flowchain-ledger'

### ISSUE THREAD

**Issue by djKooks** [flowchain/flowchain-ledger#1]
I got an issue in command `node boot.js`
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'flowchain-ledger'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kwangin/workspace/github_source/flowchain-ledger/boot.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
It looks like path of package at `var Flowchain = require('flowchain-ledger');`. need to be changed, but I could'nt find this package inside project.
Please look on.

**Comment by jollen** [comment]
@djKooks This is fixed. Please also refer to README.md for minor updates.

**Comment by djKooks** [comment]
@jollen Thanks!
