### ISSUE TITLE
ReferenceError: db is not defined

### ISSUE THREAD

**Issue by djKooks** [flowchain/flowchain-ledger#4]
I found bug like below while running `boot.js`.

```
...
----------------------
[Blockchain] no usable block now, data is ignored.
predecessor_ttl = 3
predecessor_ttl = 2
successor_ttl = 6
[Blockchain] no usable block now, data is ignored.
predecessor_ttl = 1
predecessor_ttl = 6
Difficulty: 00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
Block #1: 0078ff4ec5677a2749e99d1f39d74c6dbf7eea39cdab571c6f845ad9a9afb30b
----------------------
successor: {"address":"localhost","port":8000,"id":"e7ff381eba983a99c2489e7eeb7424b2df9347dc"}
predecessor: null
----------------------
ReferenceError: db is not defined
    at Object.onmessage (/Users/kwangin/workspace/flowchain-ledger/boot.js:56:5)
    at Automation.Server.onData (/Users/kwangin/workspace/flowchain-ledger/server/index.js:239:26)
    at emitOne (events.js:115:13)
    at WebsocketBroker.emit (events.js:210:7)
    at WebSocketConnection.onWsConnMessage (/Users/kwangin/workspace/flowchain-ledger/wot/broker.js:177:10)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/Users/kwangin/workspace/flowchain-ledger/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/kwangin/workspace/flowchain-ledger/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
```
Inside the code, I couldn't find db variable.
Could you look on?

**Comment by jollen** [comment]
@djKooks It has been fixed. Thank you!

**Comment by djKooks** [comment]
@jollen It works fine. Thanks!
